### ISSUE TITLE
02 - Création de l'entité User et resolver

### ISSUE THREAD

**Issue by RangoDisco** [WildCodeSchool/2109-wns-lyon-les4fantastiques-back#2]

**Comment by Twist974** [comment]
https://github.com/WildCodeSchool/2109-wns-lyon-les4fantastiques-back/pull/5
PR OK

**Comment by Twist974** [comment]
https://github.com/WildCodeSchool/2109-wns-lyon-les4fantastiques-back/pull/7
PR - OK
